spring:
  application:
    name: worksphere

  datasource:
    url: jdbc:mysql://localhost:3306/worksphere
    username: root
    password: Govind@2401
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080

file:
  upload-dir: uploads

jwt:
  secret: GovindWorksphereJwtSecretKey2026GovindWorksphere12345
  expiration: 86400000

logging:
  level:
    root: INFO
    com.govind.worksphere: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: TRACE

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n"